### ISSUE TITLE
can you add XAudio2

### ISSUE THREAD

**Issue by shadowtj** [CMCHTPC/DelphiDX12#13]
Is it possible you can add XAudio2 headers ? 
These can be found in when jah install unreal game engine .. under 

C:\Program Files\Epic Games\UE_4.19\Engine\Source\ThirdParty\Windows\DirectX\include\XAudio2.h

Would be perfect to have that

**Comment by CMCHTPC** [comment]
You can find the XAudio2 Headers in my WindowsAPI repository.

**Comment by shadowtj** [comment]
Thx for the reply.. will get those also :)
