### ISSUE TITLE
Delphi does not have operator overload for Initialize.

### ISSUE THREAD

**Issue by chapmanworld** [CMCHTPC/DelphiDX12#15]
Perhaps use conditionals to remove operator overloads for Initialize in Delphi. {$ifdef fpc}{$endif}

**Comment by CMCHTPC** [comment]
I'm working currently on that issue.
The class operators gets compiler conditions and extra Init procedures are added.
I'm also trying to get a example of DX12 running on Delphi 10.2 Community edtion. But I must review the whole source code cause without the class operator for the records they must be initialized manually. FPC is here  a little bit smarter :)

**Comment by CMCHTPC** [comment]
I've uploaded new version.
Delphi 10.2 is now working. Also a small example for DirectX 12 now included.
